//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.B_C_S_F = new HashSet<B_C_S_F>();
            this.C_C_T = new HashSet<C_C_T>();
            this.ElQueue = new HashSet<ElQueue>();
            this.GUE = new HashSet<GUE>();
            this.Liky = new HashSet<Liky>();
            this.PatInfo = new HashSet<PatInfo>();
        }
    
        public int Pk { get; set; }
        public string Name { get; set; }
        public string Family_Name { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Postcode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Phone_number { get; set; }
        public string Email { get; set; }
        public string Birthday { get; set; }
        public string ID { get; set; }
        public string LastVisitDate { get; set; }
        public Nullable<int> DoctorFk { get; set; }
        public string MiddleName { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<B_C_S_F> B_C_S_F { get; set; }
        public virtual ICollection<C_C_T> C_C_T { get; set; }
        public virtual Doctors Doctors { get; set; }
        public virtual ICollection<ElQueue> ElQueue { get; set; }
        public virtual ICollection<GUE> GUE { get; set; }
        public virtual ICollection<Liky> Liky { get; set; }
        public virtual ICollection<PatInfo> PatInfo { get; set; }
    }
}
