//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatInfo
    {
        public int Id { get; set; }
        public string Zhaloby { get; set; }
        public string Diagnisis { get; set; }
        public string History { get; set; }
        public Nullable<int> PatFk { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Reccomendation { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
