//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_C_T
    {
        public int Pk { get; set; }
        public string S_GLUCOSE { get; set; }
        public string S_UREA { get; set; }
        public string S_CREATININE { get; set; }
        public string S_SODIUM { get; set; }
        public string S_POTASSIUM { get; set; }
        public string S_CHLORIDE { get; set; }
        public string S_CALCIUM { get; set; }
        public string S_PHOSPHORUS { get; set; }
        public string S_MAGNESIUM { get; set; }
        public string S_CHOLESTEROL { get; set; }
        public string S_TRIGLYCERIDES { get; set; }
        public string S_HDL { get; set; }
        public string S_LDL { get; set; }
        public string S_VLDL { get; set; }
        public string S_TOTAL_PROTEINS { get; set; }
        public string S_ALBUMIN { get; set; }
        public string S_GLOBULIN { get; set; }
        public string ALGRATIO { get; set; }
        public string S_URIC_ACID { get; set; }
        public string S_T_BILIRUBIN { get; set; }
        public string DIRECT { get; set; }
        public string INDIRECT { get; set; }
        public string S_ALKALINE_PHOSPHTASE { get; set; }
        public string S_A_L_T_G_P_T__ { get; set; }
        public string S_A_S_T_G_O_T__ { get; set; }
        public string S_L_D_H { get; set; }
        public string S_C_K { get; set; }
        public string S_AMYLASE { get; set; }
        public string S_ACID_PHOSPHATASE__Total_ { get; set; }
        public string S_IRON { get; set; }
        public string T_I_B_C_ { get; set; }
        public Nullable<int> PatFk { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
