//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUE
    {
        public int Id { get; set; }
        public string Color { get; set; }
        public string Reaction { get; set; }
        public string Sugar { get; set; }
        public string Bilirubin { get; set; }
        public string Albumin { get; set; }
        public string App { get; set; }
        public string Sp_GR { get; set; }
        public string Kelones { get; set; }
        public string Urabilinogen { get; set; }
        public string RbC { get; set; }
        public string Pus_Cells { get; set; }
        public string Epithet_Cells { get; set; }
        public string Crystal { get; set; }
        public string Casts { get; set; }
        public string Mucus { get; set; }
        public string Other { get; set; }
        public string C_Parasites { get; set; }
        public Nullable<int> PatFk { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
