//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDoctor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabdesktopDBEntities : DbContext
    {
        public LabdesktopDBEntities()
            : base("name=LabdesktopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<B_C_S_F> B_C_S_F { get; set; }
        public DbSet<C_C_T> C_C_T { get; set; }
        public DbSet<Doctors> Doctors { get; set; }
        public DbSet<ElQueue> ElQueue { get; set; }
        public DbSet<GUE> GUE { get; set; }
        public DbSet<Liky> Liky { get; set; }
        public DbSet<Patient> Patient { get; set; }
        public DbSet<PatInfo> PatInfo { get; set; }
    }
}
