//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dofige.DataLibrary.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.FinanceMain = new HashSet<FinanceMain>();
            this.Subcategory = new HashSet<Subcategory>();
        }
    
        public int CatId { get; set; }
        public string CatName { get; set; }
        public Nullable<int> TypeID { get; set; }
    
        public virtual Type Type { get; set; }
        public virtual ICollection<FinanceMain> FinanceMain { get; set; }
        public virtual ICollection<Subcategory> Subcategory { get; set; }
    }
}
