//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dofige.DataLibrary.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceMain
    {
        public int FinanceMainId { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string FinanceMainNote { get; set; }
        public Nullable<int> CatID { get; set; }
        public string Created { get; set; }
        public string Modified { get; set; }
        public Nullable<int> SubCatID { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Category Category { get; set; }
        public virtual Subcategory Subcategory { get; set; }
    }
}
