//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dofige.DataLibrary.ModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategory
    {
        public Subcategory()
        {
            this.FinanceMain = new HashSet<FinanceMain>();
        }
    
        public int SubCatId { get; set; }
        public string SubCatname { get; set; }
        public Nullable<int> CatID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<FinanceMain> FinanceMain { get; set; }
    }
}
